version: '3.3'
services:

  # 1st option: Use a mariadb image with bind

  #  mariadb:
  #    image: 'bitnami/mariadb:10.3'
  #    ports:
  #      - 3306:3306
  #    volumes:
  #      - type: bind
  #        source: './mariadb_data'
  #        target: '/bitnami'
  #    environment:
  #      - MARIADB_USER=ubarnacle
  #      - MARIADB_PASSWORD=Tursiops[12]
  #      - MARIADB_DATABASE=storelightDB
  #      - MARIADB_ROOT_USER=root
  #      - MARIADB_ROOT_PASSWORD=Tursiops[12]
  #      - ALLOW_EMPTY_PASSWORD=yes
  #  storelight-main:
  #    image: barnacle/storelight-docker
  #    depends_on:
  #      - mariadb
  #    restart: on-failure
  #    hostname: storelight01
  #    ports:
  #      - 8080:8080
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:mysql://mariadb:3306/storelightDB
  #      - SPRING_DATASOURCE_USERNAME=root
  #      - SPRING_DATASOURCE_PASSWORD=Tursiops[12]
  #      - LOGGING_LEVEL_ROOT=info


  # 2nd option: Use a mysql image

#  mysql-database-kusa:
#    image: 'mysql:latest'
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=toor
#      - MYSQL_DATABASE=kusaDB
#      - MYSQL_USER=kusauser
#      - MYSQL_PASSWORD=toor
#    volumes:
#      - /data/mysql

  postgresql-db-kusa:
    image: 'bitnami/postgresql:12.4.0'
    ports:
      - '5432:5432'
    volumes:
    - './postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_DATABASE=kusa_db
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=root
      - ALLOW_EMPTY_PASSWORD=yes

  kusa-main:
    image: stahlferro/kusa-docker
    depends_on:
      - postgresql-db-kusa
    hostname: kusa-host
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-db-kusa:5432/kusa_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=kusa
    restart: on-failure

volumes:
  postgresql_master_data:
    driver: local