spring:
  datasource:
    url: ${KUSA_DB_URL}
    username: ${KUSA_DB_USERNAME}
    password: ${KUSA_DB_PASSWORD}
  data:
    rest:
      detection-strategy: annotated
  jpa:
    hibernate:
      ddl: update
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: update
              create-target: update.ddl
jwt:
  secret: ${KUSA_JWT_SECRET}
logging:
  level:
    root: INFO
test:
  testLogging:
    showStandardStreams: true
