spring:
  datasource:
    url: ${KUSA_DB_URL}
    username: ${KUSA_DB_USERNAME}
    password: ${KUSA_DB_PASSWORD}
  data:
    rest:
      detection-strategy: annotated
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    changeLog: "classpath:db/migration/liquibase-master-changelog.sql"
    databaseChangeLog:
      - includeAll:
          path: db/changelog
jwt:
  secret: ${KUSA_JWT_SECRET}
logging:
  level:
    root: INFO
test:
  testLogging:
    showStandardStreams: true
